using UnityEngine;
/// <summary>
/// Script generated by chatgpt
/// </summary>
public class transformEditor : MonoBehaviour
{
    [Header("Settings")]
    public bool useLocalSpace = false;
    public float moveSpeed = 5f;
    public float rotateSpeed = 100f;
    public float scaleSpeed = 1f;

    void Update()
    {
        HandleMovement();
        HandleRotation();
        HandleScaling();
    }

    void HandleMovement()
    {
        float moveX = Input.GetAxis("Horizontal"); // A/D or Left/Right arrows
        float moveZ = Input.GetAxis("Vertical");   // W/S or Up/Down arrows

        Vector3 move = new Vector3(moveX, 0f, moveZ) * moveSpeed * Time.deltaTime;

        if (useLocalSpace)
            transform.Translate(move, Space.Self);
        else
            transform.Translate(move, Space.World);

        // Optional: move up/down with Q/E
        Vector3 vertical = Vector3.zero;
        if (Input.GetKey(KeyCode.Q)) vertical = Vector3.down;
        if (Input.GetKey(KeyCode.E)) vertical = Vector3.up;

        if (vertical != Vector3.zero)
        {
            if (useLocalSpace)
                transform.Translate(vertical * moveSpeed * Time.deltaTime, Space.Self);
            else
                transform.Translate(vertical * moveSpeed * Time.deltaTime, Space.World);
        }
    }

    void HandleRotation()
    {
        if (Input.GetMouseButton(1)) // Right mouse button held
        {
            float mouseX = Input.GetAxis("Mouse X");
            float mouseY = Input.GetAxis("Mouse Y");

            Vector3 rotY = Vector3.up * mouseX * rotateSpeed * Time.deltaTime;
            Vector3 rotX = Vector3.right * -mouseY * rotateSpeed * Time.deltaTime;

            if (useLocalSpace)
            {
                transform.Rotate(rotX, Space.Self);
                transform.Rotate(rotY, Space.Self);
            }
            else
            {
                transform.Rotate(rotX, Space.World);
                transform.Rotate(rotY, Space.World);
            }
        }
    }

    void HandleScaling()
    {
        if (Input.GetKey(KeyCode.Equals) || Input.GetKey(KeyCode.KeypadPlus)) // '+' key
        {
            transform.localScale += Vector3.one * scaleSpeed * Time.deltaTime;
        }

        if (Input.GetKey(KeyCode.Minus) || Input.GetKey(KeyCode.KeypadMinus)) // '-' key
        {
            transform.localScale -= Vector3.one * scaleSpeed * Time.deltaTime;
        }
    }
}
